version: "3.9"

services:
  santa-app-postgres:
    image: postgres:15.4
    hostname: postgres
    container_name: santa_app_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=devonlypass
      - POSTGRES_USER=santa
    ports:
      - "5433:5433"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 3